# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
      - feature/*

pool:
  name: BUILD-0
workspace:
  clean: all

steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: custom
      verbose: false
      customCommand: 'ci --production --registry http://localhost:4873/'

  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run build'

  - task: ArchiveFiles@2
    displayName: 'Archive folder build'
    inputs:
      rootFolderOrFile: 'build\'
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
