trigger:
  branches:
    include:
      - master
      - feature/*

pool:
  vmImage: 'windows-2022'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            displayName: 'use node 14'
            inputs:
              versionSpec: 14.x
              checkLatest: true

          - checkout: self
            displayName: 'checkout'

          - task: Npm@1
            displayName: 'npm ci'
            inputs:
              command: custom
              verbose: false
              customCommand: 'ci --only=prod'

          - task: Npm@1
            displayName: 'npm build'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run build'

          - publish: $(Build.SourcesDirectory)/build
            artifact: wla
            displayName: publish artifact wla

  - stage: DeployDev
    dependsOn: Build
    jobs:
      - deployment: deployment
        displayName: 'dev.example.com'
        environment: WebsitesApp-Dev.WebsitesApp-Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: wla
                  patterns: '**/*.*'
                  displayName: download artifact wla

                - task: IISWebAppDeploymentOnMachineGroup@0
                  inputs:
                    WebSiteName: 'dev.example.com'
                    Package: '$(Pipeline.Workspace)\wla'
